import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NovaWhiteLogo from "../assets/images/nova-white-logo.svg";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="bg-gray-900 h-screen flex justify-center flex-row">
      <Head>
        <title>Nova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-4/5">
        <nav className="flex flex-row">
          <div>
            <Image src={NovaWhiteLogo} alt="nova white logo" />
          </div>

          <div className="text-white">
            <Link href="/">Join Discord</Link>
            <Link href="/signin">Sign in</Link>
          </div>
        </nav>
      </main>
    </div>
  );
};

export default Home;
