import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link"

//assets
import profilePic from '../public/profile.jpg'
import twitterIcon from '../public/twitter.svg'
import githubIcon from '../public/github.svg'
import linkedinIcon from '../public/linkedin.svg'
import NovaLogo from "../public/nova_logo.svg";

const Home: NextPage = () => {
  return (
    <div className="h-full bg-gray-900 flex flex-col items-center">
      <Head>
        <title>Nova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nova_logo.svg" />
      </Head>

      <main className="w-5/6">

        {/* nav bar */}
        <div className="flex items-center justify-between pt-4">
          <Image src={NovaLogo} alt="Nova logo" />

          <div className="text-white flex w-3/6 justify-between text-small">
            <a href="https://discord.gg/mRkzMMBc8Y" target="_blank" >Join Discord</a>
            <Link href="/signin">Sign in</Link>
          </div>
        </div>

        <div className="flex flex-col justify-center items-center h-1/4 mt-10 h-64 justify-evenly">
          <h1 className="text-white w-full font-bold text-3xl text-center">
            Hello World, I'll be grading your code
          </h1>

          <div className="bg-orange-600 rounded-md w-48 h-8 flex items-center justify-center">
            <Link href="/signup">
              <p className="text-white text-base">Try Nova for free</p>
            </Link>
          </div>

        </div>

        {/*instant codegrade section */}

        <div className="h-screen mb-20 mt-20">
          <h2 className="text-orange-600 font-bold text-xl text-center">Instant Code Grade</h2>

          <div className="flex flex-col items-center justify-around h-full">
            <div className="bg-gray-800 w-full h-52 rounded flex flex-col items-center justify-center text-center">
              <h2 className="text-white font-bold">Explanation</h2>
              <h3 className="text-white text-gray-300">
                jsdlfkjsdl;fjslfjsfjslfsl;fjlsfjdslfds
                jsdlfkjsdl;fjslfjsfjslfsl;fjlsfjdslfds
                jsdlfkjsdl;fjslfjsfjslfsl;fjlsfjdslfds
              </h3>
            </div>

            <div className="bg-gray-800 w-full h-52 rounded flex flex-col items-center justify-center text-center">
              <h2 className="text-white font-bold">Explanation</h2>
              <h3 className="text-white text-gray-300">
                jsdlfkjsdl;fjslfjsfjslfsl;fjlsfjdslfds
                jsdlfkjsdl;fjslfjsfjslfsl;fjlsfjdslfds
                jsdlfkjsdl;fjslfjsfjslfsl;fjlsfjdslfds
              </h3>
            </div>

            <div className="bg-gray-800 w-full h-52 rounded flex flex-col items-center justify-center text-center">
              <h2 className="text-white font-bold">Explanation</h2>
              <h3 className="text-white text-gray-300">
                jsdlfkjsdl;fjslfjsfjslfsl;fjlsfjdslfds
                jsdlfkjsdl;fjslfjsfjslfsl;fjlsfjdslfds
                jsdlfkjsdl;fjslfjsfjslfsl;fjlsfjdslfds
              </h3>
            </div>
          </div>
        </div>

        {/*contact section */}

        <div className="text-white">
          <h2 className="text-orange-600 font-bold text-xl text-center">Contact</h2>

          <div className="flex flex-col items-center">
            <p className="text-center">Questions? Interested? Reach out :)</p>
            <br />

            <Image src={profilePic} alt="me" width="50" height="50" className="rounded-full" />
            <p>Juan Ruiz</p>
            <p>juan@usenova.app</p>
            <p>+1 (520) 907-5458</p>
            <div className="w-2/3 pt-2 flex justify-center justify-evenly">
              <a href="https://github.com/juancaruizc" target="_blank"><Image src={githubIcon} alt="github icon" width="40" height="40" /></a>
              <a href="https://twitter.com/juanca_ruizc" target="_blank"><Image src={twitterIcon} alt="twitter icon" width="40" height="40" /></a>
              <a href="https://www.linkedin.com/in/juan-c-ruiz/" target="_blank"><Image src={linkedinIcon} alt="linkedin icon" width="40" height="40" /></a>

            </div>
          </div>
        </div>


        {/* footer */}

        <div className="flex text-white text-xs justify-around h-40 items-center">
          <div>
            <p>Terms & Conditions</p>
            <p>©2022 usenova.app</p>
          </div>

          <div>
            <p>Privacy Policy</p>
            <p> All Rights Reserved</p>
          </div>
        </div>

      </main>
    </div>
  );
};

export default Home;
