import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link"

//assets
import novaLogo from '../public/nova_logo.svg'
import profilePic from '../public/profile.jpg'
import downArrow from '../public/down_arrow.svg'

const Play: NextPage = () => {
  return (
    <div className="h-fit bg-gray-900 flex flex-col items-center lg:h-screen">
      <Head>
        <title>Play | Nova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nova_logo.svg" />
      </Head>

      <main className="w-5/6 pt-2">

        {/*nav */}
        <div className="flex justify-between">
          <Image src={novaLogo} alt="nova logo" width="45" height="45" />
          <div className="flex items-center">
            <Image src={profilePic} alt="me" width="35" height="35" className="rounded-full" />
            <p className="text-white text-sm pl-2">Juan Ruiz</p>
          </div>
        </div>

        {/*playground */}
        <section className="lg:flex lg:flex-row lg:justify-evenly">

        <div className="mt-10 h-3/4 lg:w-2/5">
          <h1 className="font-bold text-orange-600 pb-2 text-lg">Enter your code here</h1>
          <textarea className="w-full rounded h-96" placeholder="console.log('Hello World')..." />
          <div className="flex justify-end pt-4">
            <button className="bg-orange-600 text-white w-48 h-11 rounded font-bold">Submit</button>
          </div>
        </div>

        {/*results*/}
        <div className="h-80 mt-10 lg:w-2/5">
          <h1 className="font-bold text-orange-600 pb-2 text-lg">Your code results</h1>

          {/*result details section*/}
          <div className="flex flex-col h-3/4 justify-between">

            {/*exaplanation section*/}
            <div className="h-14 bg-gray-700 rounded flex justify-between items-center px-4">
              <h2 className="text-white ">Explanation</h2>
              <Image src={downArrow} alt='down arrow'width="12" height="12" />
            </div>

            {/*Optimization section*/}
            <div className="h-14 bg-gray-700 rounded flex justify-between items-center px-4">
              <h2 className="text-white ">Optimization</h2>
              <Image src={downArrow} alt='down arrow'width="12" height="12" />
            </div>


            {/*great section*/}
            <div className="h-14 bg-gray-700 rounded flex justify-between items-center px-4">
              <h2 className="text-white ">you did great on this</h2>
              <Image src={downArrow} alt='down arrow'width="12" height="12" />
            </div>

          </div>
        </div>
        </section>

      </main>
    </div>
  );
};

export default Play;
