import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link"
import React, { useState, useEffect } from 'react'
import axios from 'axios'

//assets
import novaLogo from '../public/nova_logo.svg'
import profilePic from '../public/profile.jpg'
import downArrow from '../public/down_arrow.svg'
import loadingIcon from '../public/loading_icon.gif'


const Play = () => {
  const [codeInput, setCodeInput] = useState("")
  const [codeResult, setCodeResult] = useState("")
  const [isCodeLoading, setIsCodeLoading] = useState(false)


  //POST request to OpenAI API
  const handleSubmit = async (e) => {
    e.preventDefault()
    setIsCodeLoading(true)
    const res = await fetch(`/api/grade-code`, {

      body: JSON.stringify({
        code: codeInput
      }),
      headers: {
        'Content-Type': 'application/json'
      },
      method: 'POST'
    })
    const data = await res.json();
    setCodeResult(data.codeResult);
    setCodeInput("")
    setIsCodeLoading(false)
  };


  return (
    <div className="h-fit bg-gray-900 flex flex-col items-center lg:h-screen">
      <Head>
        <title>Nova | Play</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nova_logo.svg" />
      </Head>

      <main className="w-5/6 pt-2">

        {/*nav */}
        <div className="flex justify-between">
          <Link href='/'>
            <Image src={novaLogo} alt="nova logo" width="45" height="45" />
          </Link>
          <div className="flex items-center">
            <Image src={profilePic} alt="me" width="35" height="35" className="rounded-full" />
            <p className="text-white text-sm pl-2">Juan Ruiz</p>
          </div>
        </div>

        {/*playground */}
        <section className="lg:flex lg:flex-row lg:justify-evenly">

          <div className="mt-10 h-3/4 lg:w-2/5">
            <h1 className="font-bold text-orange-600 pb-2 text-lg">Enter your code here</h1>
            <form onSubmit={handleSubmit}>
              <textarea
                className="w-full rounded h-96"
                placeholder="console.log('Hello World')..."
                value={codeInput}
                onChange={(e) => setCodeInput(e.target.value)}
              />

              <div className="flex justify-end pt-4">
                <button className="bg-orange-600 text-white w-48 h-11 rounded font-bold flex items-center justify-center">
                  {isCodeLoading ? <Image src={loadingIcon} width="20" height="20" /> : <p>Submit</p>}
                </button>
              </div>
            </form>

          </div>

          {/*results*/}
          <div className="h-fit mt-10 lg:w-2/5">
            <h1 className="font-bold text-orange-600 pb-2 text-lg">Your code results</h1>

            {/*result details section*/}
            <div className="flex flex-col h-full justify-between">

              {/*exaplanation section*/}
              <div className="h-fit bg-gray-700 rounded flex justify-between items-center px-4 flex-col mb-12">
                <div className="flex w-full justify-between py-6">
                  <h2 className="text-white font-bold">Explanation</h2>
                  <Image src={downArrow} alt='down arrow' width="12" height="12" />
                </div>

                <div className="w-full h-fit">
                  {codeResult &&
                    <p className="text-white w-full pb-8">{codeResult}</p>}
                </div>
              </div>


              {/*Optimization section*/}
              <div className="h-fit bg-gray-700 rounded flex justify-between items-center px-4 flex-col mb-12">
                <div className="flex w-full justify-between py-6">
                  <h2 className="text-white font-bold">Optimization</h2>
                  <Image src={downArrow} alt='down arrow' width="12" height="12" />
                </div>

                <div className="w-full h-fit">
                  {codeResult &&
                    <p className="text-white w-full pb-8">{codeResult}</p>}
                </div>
              </div>


              {/*great section*/}
              <div className="h-fit bg-gray-700 rounded flex justify-between items-center px-4 flex-col mb-12">
                <div className="flex w-full justify-between py-6">
                  <h2 className="text-white font-bold">Explanation</h2>
                  <Image src={downArrow} alt='down arrow' width="12" height="12" />
                </div>

                <div className="w-full h-fit">
                  {codeResult &&
                    <p className="text-white w-full pb-8">{codeResult}</p>}
                </div>
              </div>


            </div>
          </div>
        </section>

      </main>
    </div>
  );
}

export default Play;
