import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Signin: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sign up - Nova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold">Sign up</h1>
      </main>
    </div>
  );
};

export default Signin;
