import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link"

//assets
import novaLogo from '../public/nova_logo.svg'
import githubIcon from '../public/github_black.svg'

const Signin: NextPage = () => {
  return (
    <div className="h-screen bg-gray-900 flex flex-col items-center justify-center">
      <Head>
        <title>Signup | Nova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nova_logo.svg" />
      </Head>

      <main className="w-5/6 ">
        <div className="h-96 bg-gray-800 rounded flex flex-col justify-center">
          <div className="flex flex-col items-center justify-center h-4/5 justify-between">
            <Image src={novaLogo} alt="nova logo" width="50" height="50" />
            <h1 className="font-bold text-white text-lg">Sign up for Nova</h1>
            <button className="bg-white rounded w-4/5 h-10 text-sm flex items-center justify-center font-bold">
              <Image className="pr-2" src={githubIcon} alt="github icon" width="35" height="35" />Continue with Github</button>
            <div className="flex w-4/5 items-center justify-between">
              <hr className="w-1/3 bg-white" />
              <p className="text-white">or</p>
              <hr className="w-1/3 bg-white" />
            </div>
            <input className="bg-gray-700 rounded w-4/5 h-10 text-sm" placeholder="Enter your email address..." />

            <button className=" bg-orange-600 text-white w-4/5 h-10 font-bold text-sm rounded">Continue with Email</button>
          </div>

        </div>
      </main>
    </div>
  );
};

export default Signin;
